import { Edu_QLD_Beginner } from "next/font/google";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css"

const  eduQLD =  Edu_QLD_Beginner(
  {
     subsets: ["latin"] ,
    display: "swap"
 });

export const metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({ children , params }) {
  return (
    <html lang={params.lang} dir={
      params.lang === "en-us" ? 'ltr' : 'rtl'
    }
    className={params.lang === "en-us" ? eduQLD.className : eduQLD.className}
    >
      <body >{children}</body>
    </html>
  );
}
